### PR TITLE
feat(Gallery):

### PR DESCRIPTION
**Pull request by keeks5456**
- Creates the Gallery Component
- Adds a Carousel effect to the gallery images
- Adds styled component, styling.

### CODE REVIEW

**Review by AriAgress — COMMENTED** [review]
Much wow! Gallery looks amazing. Works perfectly on my end.

**Comment by AriAgress** [comment]
great work

**Comment by angelz510** [comment]
It works!

**Review by seenanadimi — COMMENTED** [review]
LGTM!

**Review by AriAgress — APPROVED** [review]
Niceeeee

**Pull request merged**
